from pathlib import Path

path = Path(r"src/agents.py")
text = path.read_text(encoding="utf-8")
old = "                            raw_json = self.extract_json(response.content)\n                            articles_data = json.loads(raw_json)\n\n                            km = KeywordManager(\n                                CONFIG_DIR / \"content_cluster_keywords.json\"\n                            )\n                            valid_clusters = [c.value for c in ContentCluster]\n\n                            for item in articles_data:\n                                text_to_check = (\n                                    item.get(\"tom_tat_noi_dung\", \"\")\n                                    + \" \"\n                                    + (item.get(\"cum_noi_dung_chi_tiet\", \"\") or \"\")\n                                ).lower()\n"
new = "                            raw_json = self.extract_json(response.content)\n                            articles_data = json.loads(raw_json)\n\n                            if not articles_data:\n                                snippet = raw_json if len(raw_json) <= 500 else f\"{raw_json[:500]}... (truncated)\"\n                                logger.warning(\n                                    f\"Batch {i // batch_size + 1} returned no articles from LLM. Raw JSON snippet: {snippet}\"\n                                )\n\n                            km = KeywordManager(\n                                CONFIG_DIR / \"content_cluster_keywords.json\"\n                            )\n                            valid_clusters = [c.value for c in ContentCluster]\n\n                            for item in articles_data:\n                                text_to_check = (\n                                    item.get(\"tom_tat_noi_dung\", \"\")\n                                    + \" \"\n                                    + (item.get(\"cum_noi_dung_chi_tiet\", \"\") or \"\")\n                                ).lower()\n"
if old not in text:
    raise SystemExit("Pattern not found")
path.write_text(text.replace(old, new), encoding="utf-8")
